version: '3.9'
services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - default

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 3ihNaKwj
    ports:
      - 5432:5432
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 3ihNaKwj
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default

  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - default

  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data
    volumes:
      - /data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 3ihNaKwj
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared
    entrypoint: 'cloudflared tunnel --no-autoupdate run'
    env_file:
      - .env
    networks:
      - default

networks:
  default:
