export {
  Approval,
  ApprovalStatus,
  Assignee,
  AssigneeType,
  Author,
  AuthorType,
  Channel,
  ChannelStatus,
  ChannelType,
  Chat,
  Contact,
  ContactField,
  ContactStatus,
  ContactTag,
  Field,
  Grant,
  Hsm,
  Media,
  MediaType,
  Message,
  MessageStatus,
  Prisma,
  Project,
  Role,
  RoleUser,
  Tag,
} from '../prisma/generated';
export * from './lib/prisma-platform.module';
export * from './lib/prisma.service';
