name: CI

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  actions: read
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: pnpm/action-setup@v3
        with:
          version: '8.15.8'

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Installing dependencies
        run: pnmp install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: master

      - name: Run commands for affected projects
        run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} pnpx nx affected --targets lint,test,container --parallel=2
